version: '3.8'

services:
  mariadb:
    image: mariadb:11.1
    container_name: hospital-auth-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_auth
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - hospital-net

volumes:
  mariadb_data:

networks:
  hospital-net:
    driver: bridge
